### ISSUE TITLE
Wrong container memory usage metric whitelisted per default for cAdvisor

### ISSUE THREAD

**Issue by tvalchev2** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#108]
[NOTE]: # " ^^ Provide a general summary of the issue in the title above. ^^ "

## Description
As described in the title the metric **container_memory_usage_bytes** is whitelisted per default. This metric includes cached files and does not represent the actual usage of a pod/container which is the relevant information for OOM Kills and memory usage (cached memory is per say free memory and can be used by the container. 
The proper metrics for that purpose would be **container_memory_rss** and specifically for OOM Kills: **container_memory_working_set_bytes**. 

## Steps to Reproduce
Install any nrotelk8s Release with important metrics definitions. Check what the **container_memory_usage_bytes** metric provides and compare the data with the data you get from kubernetes for a container/pod.

## Expected Behavior
The metric data should match the data you get from kubernetes.

## Your Environment

- Versions of your OTel collectors: 0.4.1
- Kubernetes manifest files (only the relevant configuration for important metrics for cAdvisor):
```
statefulset: 
  prometheus:
    cAdvisor:
      importantMetrics:
        - container_memory_usage_bytes
```
**container_memory_usage_bytes** - move away from using this metric in favor of **container_memory_rss** and **container_memory_working_set_bytes**. 
## Additional information
I compared the results from the **container_memory_working_set_bytes** metric and it depicts also the proper memory usage, that gets announced by kubernetes.
Relevant topic: https://forum.newrelic.com/s/hubtopic/aAX8W0000008cEUWAY/kubernetes-metric-update 

As stated above - this is a minor issue, since as of 0.4.0 the importantMetrics are exposed for customization in the values file (thanks a lot for that @utr1903 :) )

**Comment by utr1903** [comment]
@tvalchev2 Thanks for the issue, you're right! It'll be fixed in the next releases :)

**Comment by utr1903** [comment]
@tvalchev2 Implemented with following releases:

- [otel-collectors](https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/releases/tag/otel-collectors-0.7.0)
- [newrelic-monitoring](https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/releases/tag/newrelic-monitoring-0.3.0)
