### ISSUE TITLE
Implement namespace/multi-account filter for Event Logs from the Singleton collector (k8seventreceiver)

### ISSUE THREAD

**Issue by tvalchev2** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#109]
[NOTE]: # " ^^ Provide a general summary of the request in the title above. ^^ "

## Summary
We want to enable our customers and partners to be able to use NewRelic for troubleshooting purposes. That is part of our deployment observability strategy. 
Therefore we need them to be able to see kubernetes Events coming from their namespaces. At the moment the Events are being sent only to the "opsteam" NR account.

[NOTE]: # " Provide a brief overview of what the new feature is all about. "

## Desired Behavior
We want the namespace specific events to also land in the corresponding NR Accounts. This means there should be also a working filter processor for the SNG collector, which splits and sends the events as logs to the corresponding NewRelic accounts (i.e. team1 account should get the Team1 eventlogs into their own NR account from the defined namespaces under team1)

[NOTE]: # " Tell us how the new feature should work. Be specific. "
[TIP]: # " Do NOT give us access or passwords to your New Relic account or API keys! "

## Possible Solution
I really think this should be possible, as according to opentelemetry namespace should be added as a log attribute meanwhile: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23991#issuecomment-1760249834

This means it should be able to adapt a filter processor in a way, that it works similar to the statefulset collector, which also filters and splits the Logs based on the namespace attribute.

From what I understand the namespace is appended to the LogRecords attributes as `semconv.AttributeK8SNamespaceName`:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d5b99206aea1612ede64b1a60b9b0678561ccc1a/receiver/k8seventsreceiver/k8s_event_to_logdata.go#L74

Maybe this means that the namespace should not be obtained from k8s.namespace.name but there should nonetheless be possible to enrich the event Logs data with the namespace attribute, so that it can be exported to multiple accounts based on it.

[NOTE]: # " Not required. Suggest how to implement the addition or change. "

**Comment by utr1903** [comment]
@tvalchev2 Within the OTel contrib repo, the issue `32369` explained where the problem is... Such a rookie mistake. Adding the functionality immediately!

**Comment by utr1903** [comment]
Implemented with #127.
