### ISSUE TITLE
Add otlp logs pipeline for collector receiver

### ISSUE THREAD

**Issue by CJ619** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#141]
[NOTE]: # " ^^ Provide a general summary of the request in the title above. ^^ "

## Summary
It would be nice to have the ability to also export application logs via the deployment collector

[NOTE]: # " Provide a brief overview of what the new feature is all about. "

## Desired Behavior
In instances where there is a desire to integrate this solution with an otel instrument app running in k8s, it will be useful to have the ability to also export logs in otlp format through the deployment collector since it is already capable of receiving otlp metrics/traces

[NOTE]: # " Tell us how the new feature should work. Be specific. "
[TIP]: # " Do NOT give us access or passwords to your New Relic account or API keys! "
If logs are being exported from the an instrumented application, the deployment collector should be able to receive the logs and export to NR. This enhancement will be about creating a logs pipeline in the deployment collector (receiver) config

## Possible Solution
This enhancement will be about creating a logs pipeline in the deployment collector (receiver) config

[NOTE]: # " Not required. Suggest how to implement the addition or change. "

## Additional context

[TIP]: # " Why does this feature matter to you? What unique circumstances do you have? "

**Comment by utr1903** [comment]
@CJ619 Thanks a lot for the request & sorry for the delayed response. I'll implemented it asap :)

**Comment by utr1903** [comment]
Main collector variables are renamed to avoid confusion #150.

**Comment by utr1903** [comment]
Implemented with #150. It'll be in next release!

**Comment by CJ619** [comment]
Thanks @utr1903. Appreciate the good work.

**Comment by utr1903** [comment]
[0.10.0](https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/releases/tag/otel-collectors-0.10.0) has now the OTLP log pipeline within the `deployment-receiver` collector :)
