### ISSUE TITLE
Make the otlp log pipeline for deployment-receiver optional

### ISSUE THREAD

**Issue by tvalchev2** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#159]
[NOTE]: # " ^^ Provide a general summary of the request in the title above. ^^ "

## Summary
We are not using the otlp log pipeline introduced with [Added otlp log pipeline #151](https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/pull/151). However this had serious implications on the memory usage of the deployment-receiver, as it creates a processor for each otlp log pipeline, which more then doubled the memory consumption of the deployment receiver

[NOTE]: # " Provide a brief overview of what the new feature is all about. "

## Desired Behavior
You can leave it enabled by default, but please provide an option to disable the otlp log pipeline in case it is not being used. This would help us tremendously, as of right now I have to manually edit/remove the log pipeline from the collector CRD to be able to create the pod, since otherwise it uses upwards of 3-4 Gb RAM for our bigger clusters.

[NOTE]: # " Tell us how the new feature should work. Be specific. "
[TIP]: # " Do NOT give us access or passwords to your New Relic account or API keys! "

## Possible Solution
Add a flag to enable/disable this new feature.

[NOTE]: # " Not required. Suggest how to implement the addition or change. "

## Additional context

[TIP]: # " Why does this feature matter to you? What unique circumstances do you have? "

**Comment by utr1903** [comment]
Implemented with #161 and will be released today :)
