### ISSUE TITLE
Parse and enrich telemetry data with K8s manifest labels

### ISSUE THREAD

**Issue by utr1903** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#39]
@tvalchev2

## Summary

Parse the labels from the K8s manifests (pods, deployments etc.) and enrich the corresponding telemetry data with these labels. Therefore, the telemetry data can be queried according to these labels.

**Comment by utr1903** [comment]
The issue with Target Allocator using `labelmap` in Prometheus configuration is fixed per `opentelemetry-collector/1712`.

**Comment by tvalchev2** [comment]
Ach i saw that this is fixed in the opentelemetry Repo, but not yet adapted here in nrotelk8s. I was wondering why i still can't see labels ^^

**Comment by tvalchev2** [comment]
Obsolete/Implemented with:
https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/issues/137

Can be closed @utr1903
