### ISSUE TITLE
Send metrics for persistentvolumes

### ISSUE THREAD

**Issue by utr1903** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#40]
@tvalchev2

## Summary

So we are getting the metrics for the persistentvolumeclaims, but the metrics for the persistentvolumes are being dropped and not sent to NewRelic, but we need those to create dashboards and alerts, when a PV is nearing it's provisioned limit.
We see the metrics for "kube_persistentvolumeclaim_* " but not for "kube_persistentvolume_*".

Thanks in advance! :)

**Comment by utr1903** [comment]
@hodor9 I have created a new `persistentvolume` in the tet cluster and I can see that `kube_persistentvolume_*` metrics are being scraped and forwarded.

Could you verify your `kube-state-metrics` setup whether it is allowed & configured to get `persistentvolumes` metrics?

Other than that, I would recommend you to check whether you are using namespaced filtering. Since the `persistentvolumes` are non-namespaced, if you filter & export the metrics per namespaced filtering, the `persistentvolume` metrics will not be exported :)

**Comment by tvalchev2** [comment]
Yes i double checked! The metrics for `kube_persistentvolume_*` are coming. but there was no metric for `used bytes`. We thought this metric should be coming from `kube_persistentvolume_*` but it is coming from `kubelet_volume_stats*` instead.

I looked further and found out the metric we need is called `kubelet_volume_stats_used_bytes` and is coming from the `kubernetes-nodes` scraping Job.

My bad! I am sorry, this issue can be closed.
